repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: no-commit-to-branch
        args: [--branch, staging]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier

        #- repo: local
        #  hooks:
        #    - id: dtdl-validate
        #      name: dtdl-validate
        #      files: ".json"
        #      language: script
        #      entry: ./.scripts/validate.sh
